// Generated by scripts/prepare-model.mjs — do not edit by hand.
// Edit scripts/model-recipes.mjs and re-run `pnpm prepare-models`.

export const MODEL_MANIFEST = {
  "sofa-2": {
    file: "/models/sofa-2.glb",
    natural: { width: 1.68, depth: 0.703, height: 0.789 },
    slots: { carpet: "body", wood: "neutral" },
  },
} as const;
