// Generated by scripts/prepare-model.mjs — do not edit by hand.
// Edit scripts/model-recipes.mjs and re-run `pnpm prepare-models`.

export const MODEL_MANIFEST = {
  "sofa-2": {
    file: "/models/sofa-2.glb",
    natural: { width: 1.68, depth: 0.703, height: 0.789 },
    slots: { carpet: "body", wood: "neutral" },
  },
  armchair: {
    file: "/models/armchair.glb",
    natural: { width: 0.84, depth: 0.703, height: 0.789 },
    slots: { carpet: "body", wood: "neutral" },
  },
  "bed-double": {
    file: "/models/bed-double.glb",
    natural: { width: 1.6, depth: 1.883, height: 0.628 },
    slots: {
      carpet: "body",
      carpetWhite: "neutral",
      wood: "neutral",
      metal: "accent",
    },
  },
  "dining-table": {
    file: "/models/dining-table.glb",
    natural: { width: 1.6, depth: 0.851, height: 0.621 },
    slots: { wood: "body" },
  },
  wardrobe: {
    file: "/models/wardrobe.glb",
    natural: { width: 1, depth: 0.625, height: 2.125 },
    slots: { wood: "body", metal: "accent" },
  },
  credenza: {
    file: "/models/credenza.glb",
    natural: { width: 1.8, depth: 0.558, height: 0.6 },
    slots: { "": "neutral" },
  },
  "floor-lamp": {
    file: "/models/floor-lamp.glb",
    natural: { width: 0.38, depth: 0.439, height: 2.149 },
    slots: { lamp: "body", metal: "neutral" },
  },
  plant: {
    file: "/models/plant.glb",
    natural: { width: 0.45, depth: 0.422, height: 0.54 },
    slots: {
      potted_plant_02_pot: "neutral",
      potted_plant_02_leaves: "neutral",
    },
  },
  monstera: {
    file: "/models/monstera.glb",
    natural: { width: 0.8, depth: 0.728, height: 1.252 },
    slots: { "Mat.1": "neutral", "Mat.2": "neutral", material: "neutral" },
  },
  succulent: {
    file: "/models/succulent.glb",
    natural: { width: 0.17, depth: 0.187, height: 0.271 },
    slots: { potted_plant_04: "neutral" },
  },
  "plant-large": {
    file: "/models/plant-large.glb",
    natural: { width: 0.6, depth: 0.647, height: 1.379 },
    slots: {
      potted_plant_01_pot: "neutral",
      potted_plant_01_leaves: "neutral",
    },
  },
  tv: {
    file: "/models/tv.glb",
    natural: { width: 1.24, depth: 0.057, height: 0.72 },
    slots: { tv_bezel: "neutral", tv_screen: "neutral" },
  },
  "spider-table": {
    file: "/models/spider-table.glb",
    natural: { width: 2.4, depth: 1.1, height: 0.75 },
    slots: { wood: "neutral", metal: "neutral" },
  },
} as const;
